# Generated by Django 4.2.2 on 2023-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='product',
        ),
        migrations.AddField(
            model_name='productlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='appList.product'),
        ),
    ]
