# Generated by Django 4.2.2 on 2023-06-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appList', '0002_alter_category_options_remove_productlist_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
