# Generated by Django 4.2.2 on 2023-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appList', '0003_delete_productlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='appList.product')),
            ],
        ),
    ]
