# Generated by Django 4.2.2 on 2023-07-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appList', '0004_productlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
