# Generated by Django 4.2.2 on 2023-07-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appList', '0006_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ManyToManyField(to='appList.product'),
        ),
    ]
