# Generated by Django 4.2.2 on 2023-07-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appList', '0007_productlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
